apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: logto-app-kek, namespace: logto}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: vault-backend}
  target: {name: logto-app-kek, creationPolicy: Owner}
  data:
  - secretKey: SECRET_VAULT_KEK
    remoteRef: {key: logto/app, property: secret-vault-kek}
