apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lgtm-minio
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lgtm-minio
    creationPolicy: Owner
  data:
    - secretKey: LGTM_S3_ACCESS_KEY
      remoteRef: {key: secret/data/observability/lgtm-minio, property: accesskey}
    - secretKey: LGTM_S3_SECRET_KEY
      remoteRef: {key: secret/data/observability/lgtm-minio, property: secretkey}
