apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-minio
  namespace: db-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cnpg-minio
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: dr/cnpg-minio
        property: accesskey
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: dr/cnpg-minio
        property: secretkey
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: todos-db-store
  namespace: db-app
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://dr-cnpg/
    endpointURL: http://minio.polipixel.link:9000
    s3Credentials:
      accessKeyId:
        name: cnpg-minio
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-minio
        key: ACCESS_SECRET_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
