apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloud-credentials
    creationPolicy: Owner
    template:
      data:
        cloud: |                          # Velero가 기대하는 AWS 자격증명 파일 형식
          [default]
          aws_access_key_id={{ .ak }}
          aws_secret_access_key={{ .sk }}
  data:
  - secretKey: ak
    remoteRef:
      key: dr/velero-minio
      property: accesskey
  - secretKey: sk
    remoteRef:
      key: dr/velero-minio
      property: secretkey
